oreName:
  IRON_INGOT: 'Enchanted Iron Ingot'
  GOLD_INGOT: 'Enchanted Gold Ingot'
  DIAMOND: 'Enchanted Diamond'

meatName:
  COOKED_BEEF: 'Enchanted Steak'
  COOKED_CHICKEN: 'Enchanted Chicken'
  COOKED_PORKCHOP: 'Enchanted Porkchop'
  COOKED_MUTTON: 'Enchanted Mutton'