oreName:
  COAL: 'Enchanted Coal'
  RAW_IRON: 'Enchanted Raw Iron'
  RAW_GOLD: 'Enchanted Raw Gold'
  REDSTONE: 'Enchanted Redstone Dust'
  DIAMOND: 'Enchanted Diamond'
  EMERALD: 'Enchanted Emerald'
  LAPIS_LAZULI: 'Enchanted Lapis Lazuli'
